# Search Products
POST http://localhost:3000/api/search
Content-Type: application/json

{
  "hitsPerPage": 1,
  "page": 1,
  "keyword": ""
}


# Reaply Settings
POST http://localhost:3000/api/reapply-settings

# Declare Indexes
POST http://localhost:3000/api/declare-index

# Sync Products
POST http://localhost:3000/api/seed-data